// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/algorithm/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/algorithm/[id].patch').default>>>>
    }
    '/api/admin/algorithm/:id/status': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/algorithm/[id]/status.post').default>>>>
    }
    '/api/admin/algorithm': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/algorithm/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/algorithm/index.post').default>>>>
    }
    '/api/admin/donations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/donations.get').default>>>>
    }
    '/api/admin/dossiers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/dossiers.get').default>>>>
    }
    '/api/admin/dossiers/:id/audit': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/dossiers/[id]/audit.get').default>>>>
    }
    '/api/admin/dossiers/:id/complement': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/dossiers/[id]/complement.post').default>>>>
    }
    '/api/admin/dossiers/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/dossiers/[id]/index.get').default>>>>
    }
    '/api/admin/dossiers/:id/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/dossiers/[id]/messages.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/dossiers/[id]/messages.post').default>>>>
    }
    '/api/admin/dossiers/:id/reject': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/dossiers/[id]/reject.post').default>>>>
    }
    '/api/admin/dossiers/:id/start-review': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/dossiers/[id]/start-review.post').default>>>>
    }
    '/api/admin/dossiers/:id/suspend': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/dossiers/[id]/suspend.post').default>>>>
    }
    '/api/admin/dossiers/:id/validate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/dossiers/[id]/validate.post').default>>>>
    }
    '/api/admin/historique': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/historique.get').default>>>>
    }
    '/api/admin/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/messages.get').default>>>>
    }
    '/api/admin/ongs/:id/visibility': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/ongs/[id]/visibility.patch').default>>>>
    }
    '/api/admin/overview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/overview.get').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users.get').default>>>>
    }
    '/api/admin/users/:id/mandate-url': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id]/mandate-url.get').default>>>>
    }
    '/api/admin/users/:id/verify': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id]/verify.patch').default>>>>
    }
    '/api/auth/mandate-upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/mandate-upload.post').default>>>>
    }
    '/api/back-office/dossiers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/back-office/dossiers.get').default>>>>
    }
    '/api/back-office/dossiers/:id/audit': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/back-office/dossiers/[id]/audit.get').default>>>>
    }
    '/api/back-office/dossiers/:id/complement': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/back-office/dossiers/[id]/complement.post').default>>>>
    }
    '/api/back-office/dossiers/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/back-office/dossiers/[id]/index.get').default>>>>
    }
    '/api/back-office/dossiers/:id/reject': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/back-office/dossiers/[id]/reject.post').default>>>>
    }
    '/api/back-office/dossiers/:id/start-review': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/back-office/dossiers/[id]/start-review.post').default>>>>
    }
    '/api/back-office/dossiers/:id/suspend': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/back-office/dossiers/[id]/suspend.post').default>>>>
    }
    '/api/back-office/dossiers/:id/validate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/back-office/dossiers/[id]/validate.post').default>>>>
    }
    '/api/donations/:id/refund-request': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/donations/[id]/refund-request.post').default>>>>
    }
    '/api/donations/confirm-session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/donations/confirm-session.post').default>>>>
    }
    '/api/donations/create-checkout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/donations/create-checkout.post').default>>>>
    }
    '/api/donations/donor-history': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/donations/donor-history.get').default>>>>
    }
    '/api/ong-dashboard/portefeuille': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ong-dashboard/portefeuille.get').default>>>>
    }
    '/api/ongs/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ongs/[id]/index.get').default>>>>
    }
    '/api/ongs/:id/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ongs/[id]/messages.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ongs/[id]/messages.post').default>>>>
    }
    '/api/ongs/:id/partner-conversations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ongs/[id]/partner-conversations.get').default>>>>
    }
    '/api/ongs/:id/partner-messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ongs/[id]/partner-messages.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ongs/[id]/partner-messages.post').default>>>>
    }
    '/api/ongs/:id/resubmit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ongs/[id]/resubmit.post').default>>>>
    }
    '/api/ongs/:id/submit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ongs/[id]/submit.post').default>>>>
    }
    '/api/partner/conversations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/partner/conversations.get').default>>>>
    }
    '/api/partners/:id/admin-messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/partners/[id]/admin-messages.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/partners/[id]/admin-messages.post').default>>>>
    }
    '/api/score/criteria': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/score/criteria.get').default>>>>
    }
    '/api/score/ong/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/score/ong/[id].get').default>>>>
    }
    '/api/webhooks/stripe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhooks/stripe.post').default>>>>
    }
    '/api/webhooks/vanilla-pay': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhooks/vanilla-pay.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}